[package]
name = "metadata-mover"
version = "0.1.0"
authors = ["Nick Chaloult <npchaloult@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = "0.5.1"
